### ISSUE TITLE
Duplication of package

### ISSUE THREAD

**Issue by C-Entropy** [ultralisp/ultralisp#127]
I want to load [cl-str](https://github.com/vindarel/cl-str), but I got [str](https://github.com/thodg/str)
I'm using `(ql:quickload "str")`, following github page of `cl-str`
How do I get `cl-str`?

**Comment by svetlyak40wt** [comment]
Oh, this should be fixed in https://github.com/ultralisp/ultralisp/issues/73

But now cl-str is disabled because of ASDF system conflict.

I see in the database `cl-str` was added earlier:

```
ultralisp=# select id, name, created_at from project2 where name in ('thodg/str', 'vindarel/cl-str');
  id  |      name       |       created_at
------+-----------------+------------------------
   36 | vindarel/cl-str | 2019-01-28 22:21:19+00
 1426 | thodg/str       | 2020-04-11 16:36:40+00
```

Thus I've removed `thodg/str` from the main ultralisp dist and reenabled `vindarel/cl-str`.

If author of `thodg/str` want's to distribute is as part of a Quicklisp compatible dist, he can create a custom dist on Ultralisp and include `thodg/str` into it.

Sadly, there is no other way to solve ASDF systems conflicts with Quicklisp :(

@C-Entropy please update to the latest version of Ultralisp.

**Comment by C-Entropy** [comment]
Maybe add an ability to check name conflict when add new package to ultralisp? Or ability to specific link of package.Haha.

**Comment by svetlyak40wt** [comment]
This is exactly what I did in https://github.com/ultralisp/ultralisp/pull/123
