### ISSUE TITLE
Project mcclim/mcclim in ultralisp is too old

### ISSUE THREAD

**Issue by rse3vau** [ultralisp/ultralisp#156]
Hello, thanks for your great work.

I found project mcclim/mcclim in ultralisp is too old to work properly since it's last update is in Feb 2021 from branch `backend-manual`, which seems abandoned now. Loading mcclim with ultralisp installed will cause error. 

https://github.com/mcclim/mcclim/tree/backend-manual

Maybe there is something wrong? Is there anything I can help? or may I need to issue this in McCLIM's repo :)

**Comment by svetlyak40wt** [comment]
Probably, branch [backend-manual](https://github.com/mcclim/mcclim/tree/backend-manual) was default when the project was added to Ultralisp. Or maybe there are too many branches and there is a bug in Ultralisp, and it does not see `master` branch in the list. The latter is possible, because when editing the project, I see only limited number of branches in the dropdown:

<img width="899" alt="image" src="https://user-images.githubusercontent.com/24827/181747753-7f5d964f-17b9-4c46-b7e7-2ee918afce8d.png">

**Comment by svetlyak40wt** [comment]
I've updated the branch to `master` now and code should be updated to the latest soon.
