### ISSUE TITLE
Errors updating/remove new package

### ISSUE THREAD

**Issue by ChristopherBilg** [ultralisp/ultralisp#204]
`cl-opensearch-query-builder` was just added to Ultralisp yet is giving issues when I try to update it or remove it from the Ultralisp website.

Normal view: ![image](https://github.com/ultralisp/ultralisp/assets/3654150/15347ce5-e2fc-4da0-ad29-a3c45629c5b4)
Trying to remove: ![image](https://github.com/ultralisp/ultralisp/assets/3654150/bf093d43-f884-4483-ab38-c620ce132091)
Trying to edit: ![image](https://github.com/ultralisp/ultralisp/assets/3654150/33271a09-6425-411a-bd02-8a56b966bc8b)

**Comment by ChristopherBilg** [comment]
I tried adding it to the Ultralisp distribution, which errors out.

**Comment by svetlyak40wt** [comment]
Well, you don't have to add it to the main distribition. This will be done automatically after the first sources check.

Actually, it is already in the distribution since this version:

<img width="669" alt="Screenshot 2023-06-06 at 17 48 30" src="https://github.com/ultralisp/ultralisp/assets/24827/bba1ff58-3411-4c08-8e89-7979c0ffe6ce">

**Comment by ChristopherBilg** [comment]
Oh, okay. Thank you very much then 😃
