### ISSUE TITLE
Changing branch for cl-zoneinfo from main to ultralisp broke something

### ISSUE THREAD

**Issue by ak-coram** [ultralisp/ultralisp#208]
I've tried switching to the ultralisp branch for this project which gets automatically built and force-pushed for each release I make, but something broke during the process. When I open the following page, I get an error message saying 'Some shit happened':

https://ultralisp.org/projects/ak-coram/cl-zoneinfo

**Comment by svetlyak40wt** [comment]
I see there are two sources for this project both of them are pointing to the `ultralisp` branch. And there is no any error?

1. Do you still see the error?
2. Should one source be removed from the project?

**Comment by ak-coram** [comment]
> Do you still see the error?

Yes, but I have to be logged in to get it.

> Should one source be removed from the project?

Yes, one of these sources should be enough.

**Comment by ak-coram** [comment]
Yes. 

![2023-07-03-151730_1313x936_scrot](https://github.com/ultralisp/ultralisp/assets/29867035/dad605c4-6c50-4bc5-ba35-97fafdc6a660)

**Comment by svetlyak40wt** [comment]
Interesting. Because I see this page without any problems.

Will try to fix this asap.

**Comment by svetlyak40wt** [comment]
I've found the root of the problem. You've added a source of unsupported type GIT. Here is the code causing the problem – markup is incorrect and it allows to choose source type other than Git:

https://github.com/ultralisp/ultralisp/blame/aebc81f128020464d01b4aa30135875dbbd26b85/src/widgets/source.lisp#L724

But this state is not permanent yet. You can logout and login again to wipe the session and this incorrect state.

I've created a new issue about the root cause: https://github.com/ultralisp/ultralisp/issues/209

**Comment by ak-coram** [comment]
I must have clicked that by mistake. Logging out and logging in again worked!

I've removed one of the sources just now. Thank you for your help!
