### ISSUE TITLE
secrets management

### ISSUE THREAD

**Issue by atgreen** [ultralisp/ultralisp#274]
Was this intended to be public?
https://github.com/ultralisp/ultralisp/blob/591a560309c718df323673dec2245c53712c1d1c/src/server.lisp#L582

**Comment by svetlyak40wt** [comment]
Yes, these secrets are from "dev" version of the Ultralisp application. They needed to run a local version – otherwise any person who want to be able log in to the local Ultralisp instance will have to create his own GitHub application.

Secrets for production are extracted from Ansible vault during deployment.

**Comment by svetlyak40wt** [comment]
By the way, I'm going to create a documentation on Ultralisp architecture during the next week. I'll be happy if you'll review it when it will be ready.
