### ISSUE TITLE
Quicklisp daily mirror

### ISSUE THREAD

**Issue by phoe** [ultralisp/ultralisp#4]
Would it be a good idea to set up an Ultralisp dist that mimics the Quicklisp project list, except it checks for changes and rebuilds the dist every day?

The list of all projects in Quicklisp is available at https://github.com/quicklisp/quicklisp-projects/tree/master/projects - you could clone that every day and parse the entry for each directory.

**Comment by svetlyak40wt** [comment]
Counted source types for all projects in the Common Lisp’s Quickdist repository.

![2019-02-09_00-07-36](https://user-images.githubusercontent.com/24827/52506730-7c631080-2c00-11e9-93e2-50bfe9c8b850.png)

Seems I only need to support any git repository in the Ultralisp, to import 90% project from the Quicklisp!

Will work on this task on this weekend.

The plain is:

* to create an importer which will be able to import all github hosted projects: https://github.com/ultralisp/ultralisp/issues/24
* add support for any git repository (this shouldn't be very hard because GitHub already uses legit as a backend and code can be reused.
* update importer to import rest of git repositories from Quicklisp.
* do the import on production.

**Comment by svetlyak40wt** [comment]
One more note. From 1578 Quicklisp projects, 1437 are hosted on the GitHub. That is 91%. So, only 141 projects will wait for a generic git downloader.

And from these 141 project, 89 are hosted on the GitLab.com

**Comment by svetlyak40wt** [comment]
Added a function to import quicklisp projects from the REPL. Not sure if we need this automated.

**Comment by svetlyak40wt** [comment]
Imported all projects, hosted on the GitHub.

**Comment by defunkydrummer** [comment]
This is very interesting information, thanks!!
